name: Tic-Tac-Toe Game Engine

on:
  issues:
    types: [opened]

jobs:
  process-move:
    runs-on: ubuntu-latest
    concurrency: game-state
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Process game move
      run: |
        if [[ "${{ github.event.issue.title }}" =~ ^game\| ]]; then
          # Close the issue immediately for better UX
          gh issue close "${{ github.event.issue.number }}" --repo "$GITHUB_REPOSITORY" &
          
          # Extract action and position in one go
          IFS='|' read -r _ ACTION POSITION <<< "${{ github.event.issue.title }}"
          
          # Process move quickly
          if [ "$ACTION" == "move" ]; then
            python tictactoe.py move "$POSITION"
          elif [ "$ACTION" == "reset" ]; then
            python tictactoe.py reset
          fi
          
          # Update README with timestamp for cache busting
          TIMESTAMP=$(date +%s)
          sed -i "s/tic_tac_toe.svg?t=[0-9]*/tic_tac_toe.svg?t=$TIMESTAMP/" README.md
          
          # Fast commit and push
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add tic_tac_toe.svg tictactoe.json README.md
          git commit -m "🎮 Update game state" --quiet
          git push --quiet
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
