name: Tic-Tac-Toe Game Engine

on:
  issues:
    types: [opened]

jobs:
  process-move:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Process game move
      run: |
        if [[ "${{ github.event.issue.title }}" =~ ^game\| ]]; then
          # Close the issue
          gh issue close "${{ github.event.issue.number }}" --repo "$GITHUB_REPOSITORY"
          
          # Get the action (move or reset)
          ACTION=$(echo "${{ github.event.issue.title }}" | cut -d'|' -f2)
          
          if [ "$ACTION" == "move" ]; then
            POSITION=$(echo "${{ github.event.issue.title }}" | cut -d'|' -f3)
            python tictactoe.py move $POSITION
          elif [ "$ACTION" == "reset" ]; then
            python tictactoe.py reset
          fi
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update Tic-Tac-Toe game state"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
